### ISSUE TITLE
Unable to load settings error

### ISSUE THREAD

**Issue by lesaff** [cendekia/nova-setting-tool#2]
When I clicked `Install`, it briefly went to the settings page and reloads back to the main Nova Settings Tool dashboard page.

Error in the console indicates `Unable to load settings`

**Comment by Kristories** [comment]
Same here (komporin)

**Comment by cendekia** [comment]
You should run `php artisan vendor:publish --tag=settings` first

Sorry I forgot to put it in `README`

**Comment by lesaff** [comment]
OK, that did it. I also ran `artisan migrate` as well.
