### ISSUE TITLE
The Mix manifest does not exist

### ISSUE THREAD

**Issue by lesaff** [cendekia/nova-setting-tool#3]
Right after I updated my settings, I cannot see my Nova admin panel anymore.

Getting this exception

```
The Mix manifest does not exist. (View: /Users/rudy/Sites/####/vendor/cendekia/nova-setting-tool/resources/views/nova/layout.blade.php) (View: /Users/rudy/Sites/####/vendor/cendekia/nova-setting-tool/resources/views/nova/layout.blade.php)
```

**Comment by cendekia** [comment]
It's weird, I've no problem with that, I already try with new laravel nova project but the issue that you mentioned it does not appear

**Comment by dinhngocvuong** [comment]
I have the same problem as @lesaff

**Comment by cendekia** [comment]
I've found this, maybe it will help

[The Mix manifest does not exist #1352](https://github.com/JeffreyWay/laravel-mix/issues/1352#issuecomment-404208148)
