### ISSUE TITLE
What does it do?

### ISSUE THREAD

**Issue by bernhardh** [cendekia/nova-setting-tool#4]
I just installed it, but what does it do or what is it for? I thought that it is for editing .env file, but it just writes stuff in a newly created table?

**Comment by cendekia** [comment]
It is for changing the default admin panel settings, i.e app title, copyright texts, and etc
and yes it will store to `settings` table (package from unisharp/laravel-settings) and it will not accessing directly from db but from the cache once it loaded

**Comment by Kristories** [comment]
@bernhardh this is persistent key-value storage, support json and l10n.

**Comment by Kristories** [comment]
@Sparclex, I think it's okay. 

https://github.com/laravel/nova-issues/issues/99#issuecomment-416816436

> So, I emailed @taylorotwell and he did say they were planning to update that language in the terms, and that it's OK for us to modify. My guess is they'll get around to it after Laracon EU.
