### ISSUE TITLE
No entries possible. 

### ISSUE THREAD

**Issue by SDJeff** [cendekia/nova-setting-tool#5]
After Install, the save method is running before you can enter sth. in the form.

**Comment by cendekia** [comment]
@SDJeff Currently there is no validation request in the form, I'm still wondering which are the mandatory fields, do you have any suggestions?

**Comment by SDJeff** [comment]
@cendekia I think the problem was, that at https://novapackages.com/packages/cendekia/nova-setting-tool nothing is mentioned about the migration table. I saw it later in your readme.md. I did the migration manually after publishing it. Now your tool is running!

**Comment by cendekia** [comment]
@SDJeff Oh okay, actually I have problem login at https://novapackages.com ([i've submitted the issue](https://github.com/tightenco/novapackages-issues/issues/33)) so I can't edit the description yet :(

**Comment by SDJeff** [comment]
@cendekia Perhaps you can sho an error message if the table is not yet present

**Comment by cendekia** [comment]
@SDJeff thank you, I will at that condition checking later, or maybe if you would like to contributing :)
