### ISSUE TITLE
Changing the copyright is against the TOS

### ISSUE THREAD

**Issue by JapSeyz** [cendekia/nova-setting-tool#6]
Please read the terms here: https://nova.laravel.com/terms, it states that modifying the copyright notices is against the TOS.

"All copyright and proprietary notices and logos in the Control Panel and within the Software files must remain intact."

**Comment by cendekia** [comment]
@JapSeyz Please also research it more deeply about this issue

https://github.com/cendekia/nova-setting-tool/issues/4

**Comment by JapSeyz** [comment]
@cendekia I apologize, I didn't find it when I looked through the issues. I was trying to keep everyone out of breaking the TOS, but you seem to have it covered already.
